language: python
python:
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - "3.7-dev"
  - nightly
  - pypy3

services:
  - redis-server
  - mysql

env:
  matrix:
    - TRAVIS_NODE_VERSION="6"
  global:
    - secure: EVWyqwBPRDJhuJhuKXV1icevXHH4deZS1U5mF+BBJCr25Cx29uc9XnCpGkEfDpkupPf+1TW7K7yOJtfCyCqrLCEkug918WhlnYDLISqy0JdZKSQmPGod7XScQ1qFlskuTRa67g8paKBQjS9Qv2+m1tfpN8Pns2b10v++NlHF+uoPUrOnIbGXMJPOGjDt8xMs2XCf3l3Rr55D5oWoNY0swrsxgi0St/cpB028ZdYx/ZThj5phIlMEOCcvTD/HK9ZA6svHaOYtCyIxlYtDeyF00DSUTCEkNFW9a4Ke7s3Cie2XcXcepaH7O0z171T1tt1vzXkDo7bnFs9gPN+QXuM0lfJGAXbt2pTq+eo0X/mx61ypfvY/ceASR2Ikx7saxxA4vC5m9pgXcPPZeMmZqtNwBwveFQpglcLxVU5wRDEFp/QBTmSTywjNBsyaGaRP/Fx35A3L5pvu/Kd7nv84AYKwdw2US2SNZvkb6sMemocLTqL+NffCPzCjo3AuFgUiEua/83fT9xNHeJgf2MnpxEvuKQGVO83iO++uwIUuK4eLN72uylEnpwyDtX3xqLhm0vZbZtHfNjebtfa4CKsCuw9Emt1E8PZW/+XwoZoFyEMniIHX2eSsCq6LdQxuOYxRyAjD+dYssCHt0Tq7cthb0YRMKSEpueen8bQUUN5p0SQdsaA=
    - secure: Y18gI7FZyIaBQFXWzf6A4UX4sB1OqFDUCWXTNhyj2030NzsZ8o5Spu0HXO5sAzvtKP3Bph7oS4PUF7HbWE2o3VhiCPuk11AfkQgZq31yNHSSihpaGocZ6QMmb05GEFo7UAjAmpelVu1N2sRybpWg6ZNSk562jKXoVei5aA+sIWNNfP3VFfoJyDbe69yjR0qSrwKeWHROr8+h4Pvqcqv6Si6eNdaL/oO4ZXR7sDcA7bv8MGUf5Jd+AFhzsWAUwz1x4NFMta8T8rLvCNdy+uU/VNOoMsalwOHubwN7OtVtrOL9VkKcfQ0B+TzmKjo7p2FwDSYV7Ldm9KgzBiji9SiTcd3nmA5Uc8D2/s8cCQKRAZRrQaUH5wdMFz0q8kYU0VRKIVV4VZwCA9NmV+UxBmi613NDeO/Ln82G8GyNT113XrkUqs30iZ8WJC1JWZNjvFJc32Q/3FI8JqA3G1Z+EKRDboFl0UmlcuWWGEES1FwNTzmtMg2igD3B6kPMcmP9rqV87k96CXMc0Zaa8N8zmy9siQEvH2JsYKiBUtrSYVD8lJXTuJhiWCzR2qUOOKNj5lbEbXQ9DBypdi1n4ujbVT+aU4jqNylzCfvOaNh8/6PGFm1SfbD0cADjp6k//FgGHk+fbJxYMkcot0tMYX/X0UdeMpfsToStXNyZ3tGt7xoCKkc=

install:
  - virtualenv nodeps
  - ./nodeps/bin/python setup.py install
  - . ./nodeps/bin/activate
  - python setup.py install
  - pip install python-coveralls
  - pip install nose
  - pip install selenium
  - pip freeze

  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g minifier@0.8.0
  - npm install -g phantomjs-prebuilt

addons:
  apt:
    packages:
      - nginx

before_script:
  - sudo apt-get install -y -qq postfix
  - sudo service postfix start

  - sudo cp ./travis/conf/nginx.conf /etc/nginx/nginx.conf
  - sudo cat /etc/nginx/nginx.conf

  - sudo /etc/init.d/nginx restart
  - sudo ps -ef | grep nginx

  - node --version
  - which minify

  - mysql -e "DROP DATABASE IF EXISTS dp_test_db;" -u root
  - mysql -e "CREATE DATABASE IF NOT EXISTS dp_test_db;" -u root

script: ./nodeps/bin/nosetests -w ./tests

after_success:
  - coveralls
